/* ============================================================
   Bazaar — landing page behavior (framework-free)
   - Live prices: Coinbase (crypto, ~3s), Frankfurter (EUR, hourly),
     prices.json baked at deploy time (equities + oil, ~15 min)
   - Dark / light theme toggle (persisted to localStorage)
   - Glitch/flicker effect on the "without permission" box
   - Hover-to-play snek video on the same box
   - Cosmetic waitlist form
   ============================================================ */
(function () {
  "use strict";

  /* ---------- Prices ---------- */
  // Two sources, both keyless:
  //  - Crypto: Coinbase Exchange ticker (last trade), polled from the browser.
  //  - Everything else (equities, WTI, EUR): prices.json, generated by
  //    scripts/fetch-prices.py in the deploy workflow — browsers can't hit
  //    Yahoo directly (no CORS header). On file:// that fetch fails and the
  //    seeds below stay on screen.

  // Seed values so the page never shows an empty state if a source is slow/unreachable.
  var prices = {
    "BTC/USD": 65076.75, "ETH/USD": 1923.71, "TSLA/USD": 328.58, "ASML/USD": 1740.99, "SPY/USD": 773.26,
    "NVDA/USD": 223.96, "EUR/USD": 1.1535, "WTI/USD": 78.18
  };

  function fmt(pair, v) {
    if (v == null) return "—";
    if (pair === "EUR/USD") return v.toFixed(4);
    if (v >= 10000) return v.toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 });
    if (v >= 100) return v.toFixed(2);
    return v.toFixed(4);
  }

  // Update an element's price text, flashing it briefly when the value changed
  // so live ticks are visible at a glance. The flash is pure CSS (.is-tick) and
  // inert under prefers-reduced-motion.
  function setPrice(el, pair) {
    var text = prices[pair] != null ? "$" + fmt(pair, prices[pair]) : "—";
    if (el.textContent === text) return;
    el.textContent = text;
    el.classList.remove("is-tick");
    void el.offsetWidth; // restart the transition if ticks arrive back-to-back
    el.classList.add("is-tick");
    setTimeout(function () { el.classList.remove("is-tick"); }, 600);
  }

  function renderPrices() {
    document.querySelectorAll("[data-ticker]").forEach(function (el) {
      setPrice(el, el.getAttribute("data-ticker"));
    });
    document.querySelectorAll("[data-market-price]").forEach(function (el) {
      setPrice(el, el.getAttribute("data-market-price"));
    });
  }

  function fetchCrypto() {
    // Exchange ticker = actual last trade. The friendlier /v2/exchange-rates
    // endpoint is server-cached and sits still for minutes at a time.
    ["BTC", "ETH"].forEach(function (c) {
      fetch("https://api.exchange.coinbase.com/products/" + c + "-USD/ticker")
        .then(function (r) { return r.json(); })
        .then(function (d) {
          var p = d && Number(d.price);
          if (p > 0) { prices[c + "/USD"] = p; renderPrices(); }
        })
        .catch(function () { /* keep last known / seed values */ });
    });
  }

  function fetchBaked() {
    // Minute-bucketed query so each minute is a fresh CDN object — otherwise
    // Pages' 10-minute edge cache pins visitors to a stale copy. Within the
    // same minute all visitors still share one cached response.
    fetch("prices.json?t=" + Math.floor(Date.now() / 60000))
      .then(function (r) { return r.ok ? r.json() : null; })
      .then(function (d) {
        if (!d) return;
        Object.keys(prices).forEach(function (k) {
          if (Number(d[k]) > 0) prices[k] = Number(d[k]);
        });
        renderPrices();
      })
      .catch(function () {});
  }

  /* ---------- Theme toggle ---------- */
  function initTheme() {
    var root = document.documentElement;
    var toggle = document.getElementById("themeToggle");

    function current() { return root.getAttribute("data-theme") === "light" ? "light" : "dark"; }
    function apply(theme) {
      root.setAttribute("data-theme", theme);
      try { localStorage.setItem("bazaar-theme", theme); } catch (e) {}
      if (toggle) toggle.textContent = theme === "dark" ? "☀️" : "🌙";
    }

    if (toggle) {
      toggle.textContent = current() === "dark" ? "☀️" : "🌙";
      toggle.addEventListener("click", function () {
        apply(current() === "dark" ? "light" : "dark");
      });
    }
  }

  /* ---------- Glitch box + hover video ---------- */
  function initGlitch() {
    var box = document.getElementById("glitchBox");
    var video = document.getElementById("glitchVideo");
    if (!box) return;

    var hovered = false;
    var glitchTimer = null;
    var glitchOffTimer = null;
    var lastPlayed = 0;
    var COOLDOWN_MS = 1000;

    function schedule() {
      if (hovered) return;
      var delay = 2000 + Math.random() * 2000;
      glitchTimer = setTimeout(function () {
        if (hovered) return;
        box.classList.add("is-glitching");
        glitchOffTimer = setTimeout(function () {
          box.classList.remove("is-glitching");
          schedule();
        }, 400);
      }, delay);
    }

    function endHover() {
      if (!hovered) return;
      hovered = false;
      box.classList.remove("is-hovering");
      if (video) { try { video.pause(); } catch (e) {} }
      schedule();
    }

    function startPlay() {
      var now = Date.now();
      if (now - lastPlayed < COOLDOWN_MS) return;
      lastPlayed = now;
      clearTimeout(glitchTimer);
      clearTimeout(glitchOffTimer);
      hovered = true;
      box.classList.remove("is-glitching");
      box.classList.add("is-hovering");
      if (video) {
        try {
          video.currentTime = 0;
          video.muted = true;
          var p = video.play();
          if (p && p.catch) p.catch(function () {});
        } catch (e) {}
      }
    }

    box.addEventListener("mouseenter", startPlay);

    // Touch devices have no hover — let a tap play the snek video, then it
    // ends on its own via the "ended" handler below. Gated to no-hover
    // pointers so desktop mouse taps don't double-fire alongside mouseenter.
    var touchOnly = window.matchMedia && window.matchMedia("(hover: none)").matches;
    box.addEventListener("click", function () {
      if (touchOnly) startPlay();
    });

    box.addEventListener("mouseleave", endHover);
    if (video) video.addEventListener("ended", endHover);

    schedule();
  }

  /* ---------- Confetti burst (dependency-free) ---------- */
  function fireConfetti(originEl) {
    if (window.matchMedia && window.matchMedia("(prefers-reduced-motion: reduce)").matches) return;

    var colors = ["#FDE000", "#ffffff", "#000000", "#22d3ee", "#ef4444"];
    var canvas = document.createElement("canvas");
    canvas.style.cssText = "position:fixed;inset:0;width:100vw;height:100vh;pointer-events:none;z-index:9999;";
    document.body.appendChild(canvas);
    var ctx = canvas.getContext("2d");
    var dpr = Math.min(window.devicePixelRatio || 1, 2);
    function size() { canvas.width = innerWidth * dpr; canvas.height = innerHeight * dpr; ctx.setTransform(dpr, 0, 0, dpr, 0, 0); }
    size();

    // Burst originates from the target element's center (fallback: screen center).
    var ox = innerWidth / 2, oy = innerHeight / 2;
    if (originEl) { var r = originEl.getBoundingClientRect(); ox = r.left + r.width / 2; oy = r.top + r.height / 2; }

    var N = 140, parts = [];
    for (var i = 0; i < N; i++) {
      var ang = Math.PI * 2 * (i / N) + (Math.random() - 0.5);
      var speed = 6 + Math.random() * 9;
      parts.push({
        x: ox, y: oy,
        vx: Math.cos(ang) * speed, vy: Math.sin(ang) * speed - 4,
        w: 6 + Math.random() * 6, h: 8 + Math.random() * 8,
        rot: Math.random() * Math.PI, vr: (Math.random() - 0.5) * 0.4,
        color: colors[(Math.random() * colors.length) | 0],
        life: 0, ttl: 90 + Math.random() * 50
      });
    }

    var frame = 0, maxFrames = 160;
    function tick() {
      ctx.clearRect(0, 0, innerWidth, innerHeight);
      var alive = false;
      for (var i = 0; i < parts.length; i++) {
        var p = parts[i];
        if (p.life > p.ttl) continue;
        alive = true;
        p.life++;
        p.vy += 0.35;            // gravity
        p.vx *= 0.99;            // drag
        p.x += p.vx; p.y += p.vy; p.rot += p.vr;
        ctx.save();
        ctx.translate(p.x, p.y);
        ctx.rotate(p.rot);
        ctx.globalAlpha = Math.max(0, 1 - p.life / p.ttl);
        ctx.fillStyle = p.color;
        ctx.fillRect(-p.w / 2, -p.h / 2, p.w, p.h);
        ctx.restore();
      }
      frame++;
      if (alive && frame < maxFrames) requestAnimationFrame(tick);
      else remove();
    }
    var removed = false;
    function remove() { if (!removed) { removed = true; canvas.remove(); } }
    requestAnimationFrame(tick);
    setTimeout(remove, 5000); // hard fallback if rAF is throttled (backgrounded tab)
  }

  /* ---------- Waitlist (cosmetic) ---------- */
  function initWaitlist() {
    var form = document.getElementById("waitlistForm");
    var success = document.getElementById("waitlistSuccess");
    if (!form || !success) return;
    // The form POSTs to Brevo via the hidden "brevo_iframe" (see target attr), so the
    // page never navigates away. Native validation blocks invalid emails before submit
    // fires, so this only runs once a valid address is on its way to Brevo.
    form.addEventListener("submit", function () {
      form.hidden = true;
      form.style.display = "none";
      success.hidden = false;
      fireConfetti(success);
      countEvent("waitlist-signup", "Waitlist signup");
    });
  }

  /* ---------- Price ticker: seamless infinite marquee ---------- */
  // The CSS animation shifts the track by -50%, i.e. exactly one half. That only looks
  // seamless while one half is at least as wide as the viewport — otherwise the content
  // runs out and visibly snaps back. So repeat the unique item set until each half
  // overflows the screen, keeping the two halves identical.
  function initTicker() {
    var track = document.getElementById("tickerTrack");
    if (!track) return;

    var unique = [].slice.call(track.children)
      .filter(function (el) { return !el.hasAttribute("aria-hidden"); });
    if (!unique.length) return;

    var SPEED = 60; // px per second

    function build() {
      var unitW = unique.reduce(function (sum, el) { return sum + el.getBoundingClientRect().width; }, 0);
      if (!unitW) return;

      var reps = Math.max(1, Math.ceil(window.innerWidth / unitW));
      var halfW = unitW * reps;

      var frag = document.createDocumentFragment();
      for (var copy = 0; copy < 2; copy++) {
        for (var r = 0; r < reps; r++) {
          for (var i = 0; i < unique.length; i++) {
            var node = unique[i].cloneNode(true);
            // Only the first copy is exposed to assistive tech; the rest are decorative.
            if (copy === 0 && r === 0) node.removeAttribute("aria-hidden");
            else node.setAttribute("aria-hidden", "true");
            frag.appendChild(node);
          }
        }
      }

      track.textContent = "";
      track.appendChild(frag);
      track.style.animationDuration = (halfW / SPEED) + "s";
      renderPrices(); // re-fill the freshly cloned nodes
    }

    build();

    var t = null, lastW = window.innerWidth;
    window.addEventListener("resize", function () {
      if (window.innerWidth === lastW) return; // ignore mobile scroll-driven resizes
      lastW = window.innerWidth;
      clearTimeout(t);
      t = setTimeout(build, 200);
    });
  }

  /* ---------- Features marquee: auto-scroll + drag ---------- */
  function initFeatures() {
    var viewport = document.querySelector(".features");
    var track = document.querySelector(".features__track");
    if (!viewport || !track) return;

    // Respect reduced-motion: leave the CSS fallback (native overflow scroll) alone.
    if (window.matchMedia && window.matchMedia("(prefers-reduced-motion: reduce)").matches) return;

    var SPEED = 45;          // px per second of auto-scroll
    var offset = 0;          // current translateX magnitude (content moves left as this grows)
    var half = 0;            // width of one copy of the card set (track holds two copies)
    var dragging = false;
    var startX = 0;
    var startOffset = 0;
    var lastT = 0;

    function measure() { half = track.scrollWidth / 2; }
    function wrap(v) { return half > 0 ? ((v % half) + half) % half : 0; }
    function apply() { track.style.transform = "translateX(" + (-offset) + "px)"; }

    measure();
    window.addEventListener("resize", function () { measure(); offset = wrap(offset); apply(); });

    function frame(t) {
      if (!lastT) lastT = t;
      var dt = (t - lastT) / 1000;
      lastT = t;
      if (!dragging) { offset = wrap(offset + SPEED * dt); apply(); }
      requestAnimationFrame(frame);
    }
    requestAnimationFrame(frame);

    track.addEventListener("pointerdown", function (e) {
      dragging = true;
      startX = e.clientX;
      startOffset = offset;
      track.classList.add("is-dragging");
      try { track.setPointerCapture(e.pointerId); } catch (err) {}
    });

    track.addEventListener("pointermove", function (e) {
      if (!dragging) return;
      // Drag right → content follows the pointer right → offset decreases.
      offset = wrap(startOffset - (e.clientX - startX));
      apply();
    });

    function endDrag(e) {
      if (!dragging) return;
      dragging = false;
      track.classList.remove("is-dragging");
      try { track.releasePointerCapture(e.pointerId); } catch (err) {}
    }
    track.addEventListener("pointerup", endDrag);
    track.addEventListener("pointercancel", endDrag);
  }

  /* ---------- Analytics ---------- */
  // GoatCounter events. These are counted separately from pageviews and show up under
  // their own paths in the dashboard. count.js loads async and is a routine ad-block
  // target, so every call is guarded — a missing counter must never break a click.
  function countEvent(path, title) {
    var gc = window.goatcounter;
    if (!gc || typeof gc.count !== "function") return;
    try {
      gc.count({ path: path, title: title, event: true });
    } catch (e) {}
  }

  // Delegated, so it covers every copy of a link without touching the markup: Docs
  // appears three times and GitHub twice, and clicks frequently land on the inline
  // SVG inside the footer links rather than on the anchor itself.
  function initAnalytics() {
    document.addEventListener("click", function (e) {
      var el = e.target;
      var a = el && el.closest ? el.closest("a") : null;
      if (!a) return;
      var href = a.getAttribute("href") || "";
      if (href.indexOf("github.com") > -1) countEvent("click-github", "GitHub");
      else if (href.indexOf("docs.bazaar.finance") > -1) countEvent("click-docs", "Docs");
      else if (href === "#waitlist") countEvent("click-waitlist-cta", "Waitlist CTA");
    });
  }

  /* ---------- Boot ---------- */
  function boot() {
    initTheme();
    initAnalytics();
    initGlitch();
    initWaitlist();
    initFeatures();
    initTicker();
    renderPrices();
    fetchCrypto();
    fetchBaked();
    setInterval(fetchCrypto, 3000);   // Coinbase: well under their per-IP limit
    setInterval(fetchBaked, 60000);   // ~250 bytes/min; redeployed every ~5 min
  }

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", boot);
  } else {
    boot();
  }
})();
